#Data on which hier_alt.py was run on 

cd /gpfs/commons/groups/knowles_lab/Cas13Karin
module load python/3.7.1  

#Essential genes only and common junctions only 

seabass_run=/gpfs/commons/home/kisaev/seabass/src/run_hier_alt.py 

#1. all replicates and LFCs generated using Harm's script and batch corrected counts 
input_file=/gpfs/commons/groups/knowles_lab/Cas13Karin/data/2021-11-21_HWcode_screen_R1_include/2021-11-21_R1_include_KI_LFC_all_guides_Harm_Code.txt.gz
name_analysis=R1_include_HW_code
output_dir=/gpfs/commons/groups/knowles_lab/Cas13Karin/analysis/seabass/

python $seabass_run $input_file $name_analysis $output_dir

#2. Same as above but without replicate 1 values 
input_file=/gpfs/commons/groups/knowles_lab/Cas13Karin/data/2021-11-21_HWcode_screen_R1_remove/2021-11-21_R1_remove_KI_LFC_all_guides_Harm_Code.txt.gz
name_analysis=R1_remove_HW_code
output_dir=/gpfs/commons/groups/knowles_lab/Cas13Karin/analysis/seabass/

python $seabass_run $input_file $name_analysis $output_dir

#3. all replicates and LFCs generated by MAGECK test 

#4. same as above but without replicate 1 values 