#Data on which hier_alt.py was run on 

#Essential genes only and common junctions only 

#1. all replicates and LFCs generated using Harm's script and batch corrected counts 

#2. Same as above but without replicate 1 values 

#3. all replicates and LFCs generated by MAGECK test 

#4. same as above but without replicate 1 values 